### ISSUE TITLE
Cannot access `/static` on production

### ISSUE THREAD

**Issue by bernatesquirol** [shamsup/remix-starter-serverless#4]
Thanks for the shared work. Although I can access offline, and everything works, when I try to deploy, I get a 404 when trying to access the created bucket. It seems like `static` redirection doesn't work properly. 
The S3 bucket is created properly and with the same files that are requested by the client.

![image](https://user-images.githubusercontent.com/4685790/169373239-807c376a-6d52-4047-8469-ec97522684a3.png)

**Comment by shamsup** [comment]
Hey, looks like it is redirecting to the API gateway endpoint instead of the cloudfront endpoint. Check the section in the Readme about setting the X-Forwarded-Host header: https://github.com/shamsup/remix-starter-serverless#limitations-and-first-deployment-configuration

**Comment by bernatesquirol** [comment]
I was accessing myself to the API getaway instead of the cloudfront 🙄. Thanks!

When configuring the X-Forwarded-Host I do get a 
`An error occurred: CDN - Properties validation failed for resource CDN with message:  #/DistributionConfig/Origins/1/OriginCustomHeaders/0/HeaderValue: expected type: String, found: JSONObject.`

which gets fixed with 
`HeaderValue: ${self:custom.${self:provider.stage}.HOST}`
