### ISSUE TITLE
Value not found at "self" source

### ISSUE THREAD

**Issue by tgandee79** [shamsup/remix-starter-serverless#6]
I've been following the example from the README and when I uncomment the `OriginCustomHeaders` section, I get the error below when running `sls deploy --stage dev` or `npm run deploy` which is set to `sls deploy`:

```
 - Cannot resolve variable at "resources.Resources.CDN.Properties.DistributionConfig.Origins.1.OriginCustomHeaders.0.HeaderValue": Value not found at "self" source
 ```

my dev settings for host are set from the initial output of `sls info --verbose`. 

I am completely new SLS, so I'm not sure where I'm going wrong variable settings.

**Comment by shamsup** [comment]
There is a typo in the commented block. If you change it to `HeaderValue: ${self:custom.${self:provider.stage}.HOST}` it will work.

**Comment by tgandee79** [comment]
Thanks.  I actually used ChatGPT to help me solve the issues
With the following config, it deploys, but I'm still not getting assets loading from the AWS link.  I'll keep digging.

`OriginCustomHeaders:
                - HeaderName: X-Forwarded-Host
                  HeaderValue:  ${self:custom.${self:provider.stage}.HOST}`

**Comment by tgandee79** [comment]
The typo fixed the deploys. I am still not seeing the remix and other assets load, but this issue is resolved.
